### PR TITLE
Implementing CPU usage calculation

### PR DESCRIPTION
**Pull request by r3na**

### CODE REVIEW

**Comment by robertsLando** [comment]
@r3na Thanks for your PR, please fix ci and remember to also write a test for the new feature

**Comment by r3na** [comment]
@robertsLando  done
reference:
https://gist.github.com/bag-man/5570809

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by r3na** [comment]
sorry, I felt the need to implement this one as well
https://nodejs.org/api/os.html#os_os_loadavg  

@mcollina @robertsLando

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by robertsLando** [comment]
@r3na  Can I merge this or would you like to add some other stat?

**Comment by r3na** [comment]
@robertsLando i am done :D

**Pull request merged**
